  json.id activity.id
  json.name activity.name
  json.description activity.description
  json.country activity.country
  json.city activity.city
  json.created_at activity.created_at
  json.category activity.category.name
  json.likesCount activity.likes.pluck(:id)
  json.commentsCount activity.comments.count
  json.thumbnail url_for(activity.thumbnail)